version: 2
jobs:
  build:
    docker:
      - image: circleci/node:dubnium
    working_directory: ~/repo
    steps:
      - checkout
      - restore_cache:
        keys:
          - v1-depenencies-{{checksum "package.json"}}
          - v1-depenencies-
      
      - run: npm install

      - save_cache:
        paths: 
          - node_modules
        key: v1-dependencies-{{checksum "package.json"}}
      
      - run: build:ci